language: cpp
jobs:
  include:
    - stage: "Building"
    
      name: "Building"
      os: linux
      compiler: gcc
      script:
        - wc -l matrixoperations.c
        - gcc -fPIC -c matrixoperations.c -o matrixoperations.o
        - gcc -shared matrixoperations.o -o libmatrixoperations.so
        - gcc -I`pwd` -L`pwd` main.c -lmatrixfact -o prog
        
        
    - stage: Documentation
    
      name: "Documentation"
      os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install doxygen
      script:
        - git clone https://github.com/Astray68/BoSE_Git.git
        - mv Doxyfile matrixoperations.c Doxygen/
        - cd Doxygen
        - doxygen
        - rm Doxyfile matrixoperations.c
        - git config --global user.name "travis"
        - git config --global user.email "silverxvost@gmail.com"
        - git add -A
        - git commit -am "Update doc from Travis CI"
        - git config --global push.default simple
        - git push -f -q  https://Astray68:${GITHUB_API_KEY}@github.com/Astray68/Doxygen.git
